# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories

version: 2

updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 15
    directory: "/"
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 15
    directories:
      - "**/*"
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: "daily"
    groups:
      fiber-modules:
        patterns:
          - "github.com/gofiber/fiber/**"
      fasthttp-modules:
        patterns:
          - "github.com/valyala/fasthttp"
          - "github.com/valyala/fasthttp/**"
      golang-modules:
        patterns:
          - "golang.org/x/**"
  - package-ecosystem: "npm"
    open-pull-requests-limit: 15
    directories:
      - "**/*"
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    open-pull-requests-limit: 15
    directories:
      - "**/*"
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: "daily"
